theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: MICROS Workshop @ CIKM 2022 
description: Workshop on Mixed-Initiative ConveRsatiOnal Systems 2022

google_analytics: UA-36357044-1

plugins:
- jekyll-menus
