theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: MICROS Workshop 2021 
description: Workshop on Mixed-Initiative ConveRsatiOnal Systems ( MICROS @ ECIR 2021 )

plugins:
- jekyll-menus
