theme: jekyll-theme-leap-day
# theme: jekyll-theme-cayman

title: MICROS Workshop @ ECIR 2021 
description: Workshop on Mixed-Initiative ConveRsatiOnal Systems 2021

google_analytics: UA-36357044-1

plugins:
- jekyll-menus
